version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_HOST=localhost:8000

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app